<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Bint Al Sahraa Jewellery Trading LLC</title>
    <link rel="stylesheet" href="style.css">
 <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Bungee&family=Bungee+Spice&family=Handjet:wght@300&family=Russo+One&display=swap" rel="stylesheet">

  </head>
  <body>
<img src="RS.PNG" alt="Trulli" style="float:left;width:70px;height:70px border-radius: 6px;
margin-left: 75px;margin-top: 5px;">
<div class="rs"> RS GROUP </div>
<img src="bint.PNG" alt="Trulli" style="float:left;width:42px;height:42px border-radius: 6px;
margin-left: 75px;">



<div class="head">Bint Al Sahraa Jewellery Trading LLC</div>
<div id="main">
<h2 style="color:red";margin-left:75px; class="symbol">Sell USD TTBAR</h2>


  <label for="marginlevel"class="fontstyle">MARGIN LEVEL</label><br>
  <input type="text" class="box" id="marginlevel" name="marginlevel" placeholder="200%" value="" onchange="myFunction()"><br>
  <label for="rate"class="fontstyle">Current Rate</label><br>
  <input type="text" class="box" id="rate" name="rate" placeholder="1950" value="" onchange="myFunction()"><br><br>




<b type="text" id="marginl"value=""></b>

<br><br>
<button onclick="CFunction()" id="copybutton"class="ripple" >COPY TEXT</button>

<!--   Sell in gram -->
<!--
<h2 class="symbol" style="color:red";>Sell GRAM</h2>


  <label for="grammarginlevel"class="fontstyle">MARGIN LEVEL</label><br>
  <input type="text" class="box" id="grammarginlevel" name="grammarginlevel" placeholder="200%" value="" onchange="GramFunction()"><br>
  <label for="rate"class="fontstyle">Current Rate</label><br>
  <input type="text" class="box" id="rategram" name="rate" placeholder="1950" value="" onchange="GramFunction()"><br><br>




<b type="text" id="gramoutput"value=""></b>
<br><br>
<button onclick="GramcopyF()" id="copybutton"class="ripple">COPY TEXT</button>
 -->


<!--   Sell Traditional method-->

<h2 class="symbol" style="color:red";>Sell GRAM Traditional Method</h2>


  <label for="grammarginlevelT"class="fontstyle">Position Weight</label><br>
  <input type="text" class="box" id="Tposition" name="Tposition" placeholder="500 Gram" value="" onchange="SellTrad()"><br>
  <label for="Equitygram"class="fontstyle">Equity</label><br>
  <input type="text" class="box" id="equitysell" name="equitysell" placeholder="5000 $" value="" onchange="SellTrad()"><br>
  <label for="rate"class="fontstyle">Current Rate</label><br>
  <input type="text" class="box" id="rategramTr" name="rategramTr" placeholder="1950" value="" onchange="SellTrad()"><br><br>




<b type="text" id="Tgramoutputsell"value=""></b>
<br><br>
<button onclick="TGramcopyF()" id="Tcopybutton"class="ripple">COPY TEXT</button>




















<!-- Buy LIMIT -->

<h2 class="symbol" style="color:green";>Buy USD TTBAR</h2>


  <label for="marginleveb"class="fontstyle">MARGIN LEVEL</label><br>
  <input type="text" class="box" id="marginleveb" name="marginleveb" placeholder="200%" value="" onchange="Bunction()"><br>
  <label for="rate"class="fontstyle">Current Rate</label><br>
  <input type="text" class="box" id="ratve" name="ratve" placeholder="1950" value="" onchange="Bunction()"><br><br>




<b type="text" id="Buyminl"value=""></b>
<br><br>
<button onclick="BFunction()" id="copybutton"class="ripple">COPY TEXT</button>




<!-- Buy LIMIT for gram -->
<!--
<h2 class="symbol" style="color:green">Buy GRAM</h2>


  <label for="grambuymargin"class="fontstyle">MARGIN LEVEL</label><br>
  <input type="text" class="box" id="grambuymargin" name="grambuymargin" placeholder="200%" value="" onchange="Buygram()"><br>
  <label for="buyrate"class="fontstyle">Current Rate</label><br>
  <input type="text" class="box" id="buyrate" name="buyrate" placeholder="1950" value="" onchange="Buygram()"><br><br>




<b type="text" id="buygramoutput"value=""></b>
<br><br>
<button onclick="buygramcopy()" id="copybutton"class="ripple">COPY TEXT</button>
 -->



<!--   BUY Traditional method-->

<h2 class="symbol" style="color:green";>Buy GRAM Traditional Method</h2>


  <label for="gramBuyTr"class="fontstyle">Position Weight</label><br>
  <input type="text" class="box" id="Tpositionbuy" name="Tpositionbuy" placeholder="500 Gram" value="" onchange="BuyTrad()"><br>
  <label for="Equitygram"class="fontstyle">Equity</label><br>
  <input type="text" class="box" id="equitybuy" name="equitybuy" placeholder="5000 $" value="" onchange="BuyTrad()"><br>
  <label for="rate"class="fontstyle">Current Rate</label><br>
  <input type="text" class="box" id="ratebuyTr" name="ratebuyTr" placeholder="1950" value="" onchange="BuyTrad()"><br><br>




<b type="text" id="TrBuy"value=""></b>
<br><br>
<button onclick="TGramBuy()" id="Tcopybutton"class="ripple">COPY TEXT</button>








<!-- Buy LIMIT for Ounce -->

<h2 class="symbol" style="color:green">Buy Ounce</h2>


  <label for="lotsize"class="fontstyle">Ounce Lot Size</label><br>
  <input type="text" class="box" id="grambuymarginounce" name="grambuymarginounce" placeholder="2" value="" onchange="Buyounce()"><br>
  <label for="buyozrate"class="fontstyle">Current Rate</label><br>
  <input type="text" class="box" id="buyouncerate" name="buyouncerate" placeholder="1850" value="" onchange="Buyounce()"><br>
  <label for="Equity"class="fontstyle">Equity</label><br>
  <input type="text" class="box" id="buyounceequity" name="buyounceequity" placeholder="2000" value="" onchange="Buyounce()"><br><br>




<b type="text" id="buyounceoutputt"value=""></b>
<br><br>
<button onclick="buyouncecopy()" id="copyouncebuybutton"class="ripple">COPY TEXT</button>




<!-- Sell LIMIT for Ounce -->

<h2 class="symbol" style="color:red";margin-left:75px; class="symbol">Sell Ounce</h2>


  <label for="lotsize"class="fontstyle">Ounce Lot Size</label><br>
  <input type="text" class="box" id="sellounce" name="sellounce" placeholder="2" value="" onchange="Sellounce()"><br>
  <label for="buyozrate"class="fontstyle">Current Rate</label><br>
  <input type="text" class="box" id="sellouncerate" name="sellouncerate" placeholder="1850" value="" onchange="Sellounce()"><br>
  <label for="Equity"class="fontstyle">Equity</label><br>
  <input type="text" class="box" id="sellounceequity" name="sellounceequity" placeholder="2000" value="" onchange="Sellounce()"><br><br>




<b type="text" id="sellounceoutputt"value=""></b>
<br><br>
<button onclick="sellouncecopy()" id="sellounceoutputt"class="ripple">COPY TEXT</button>








</div>



<script>
<!-- sell limit for usdttbar -->
function myFunction() {
var margin = Number(document.getElementById("marginlevel").value);

var rate=Number(document.getElementById("rate").value);

var limit=Math.ceil(rate+((margin*1.5)*0.17999)-5);
if (margin < 100) {document.getElementById("marginl").innerHTML ="*âš ï¸WARNING: Your Margin Level is BELOWâ¬‡ï¸ SAFE LEVEL and it is : " +margin +"% and Your ACCOUNT LIMIT is : "+limit +"ðŸ’² To Avoid ðŸ…¾ï¸Liquidation PLEASE ðŸ’µDEPOSIT*";}
else{
document.getElementById("marginl").innerHTML ="*Your Margin Level is : " +margin +"% and Your ACCOUNT LIMIT is : "+limit +"ðŸ’²*";
}
}
function CFunction() {
  // Get the text field
  var copyText = document.getElementById("marginl");

  // Select the text field
  copyText.select;
// For mobile devices

  // Copy the text inside the text field
  navigator.clipboard.writeText(copyText.innerHTML);


}



<!-- sell limit for gram -->


function GramFunction() {
var grammarginlevel = Number(document.getElementById("grammarginlevel").value);

var rategram=Number(document.getElementById("rategram").value);

var sellgramlimit=Math.ceil(rategram+((grammarginlevel*1.5)*0.19511)-5);
if (grammarginlevel < 100) {document.getElementById("gramoutput").innerHTML ="*âš ï¸WARNING: Your Margin Level is BELOWâ¬‡ï¸ SAFE LEVEL and it is : " +grammarginlevel +"% and Your ACCOUNT LIMIT is : "+sellgramlimit +" ðŸ’² To Avoid ðŸ…¾ï¸Liquidation PLEASE ðŸ’µDEPOSIT*";}
else{
document.getElementById("gramoutput").innerHTML ="*Your Margin Level is : " +grammarginlevel +"% and Your ACCOUNT LIMIT is : "+sellgramlimit +"ðŸ’²*";
}

}
function GramcopyF() {
  // Get the text field
  var copyText = document.getElementById("gramoutput");

  // Select the text field
  copyText.select;
// For mobile devices

  // Copy the text inside the text field
  navigator.clipboard.writeText(copyText.innerHTML);


}


<!--   Sell gm Traditional method-->


function SellTrad() {
var Tsellposition = Number(document.getElementById("Tposition").value);

var RateTr=Number(document.getElementById("rategramTr").value);

var EquityTS=Number(document.getElementById("equitysell").value);

var sellgramlimitTr=Math.ceil(RateTr+((EquityTS*31.1035)/Tsellposition)-5);
var warningmessage=Math.ceil((EquityTS*31.1035)/Tsellposition);
if (warningmessage < 35) {document.getElementById("Tgramoutputsell").innerHTML ="*âš ï¸WARNING: Your Account Status is BELOWâ¬‡ï¸ SAFE LEVEL and Your Equity is : " +EquityTS +" $ and Your ACCOUNT LIMIT is : "+sellgramlimitTr +" ðŸ’² To Avoid ðŸ…¾ï¸Liquidation PLEASE ðŸ’µDEPOSIT*";}
else{
document.getElementById("Tgramoutputsell").innerHTML ="*Your Equity is : " +EquityTS +" $ and Your ACCOUNT LIMIT is : "+sellgramlimitTr +"ðŸ’²*";
}

}
function TGramcopyF() {
  // Get the text field
  var copyText = document.getElementById("Tgramoutputsell");

  // Select the text field
  copyText.select;
// For mobile devices

  // Copy the text inside the text field
  navigator.clipboard.writeText(copyText.innerHTML);


}











<!-- Buy limit for Usdttbar -->


function Bunction() {
var marginleveb = Number(document.getElementById("marginleveb").value);

var ratve=Number(document.getElementById("ratve").value);

var Buyli=Math.ceil((ratve-((marginleveb*1.5)*0.17999))+5);
if (marginleveb < 100) {document.getElementById("Buyminl").innerHTML ="*âš ï¸WARNING: Your Margin Level is BELOWâ¬‡ï¸ SAFE LEVEL and it is : " +marginleveb +"% and Your ACCOUNT LIMIT is : "+Buyli +"ðŸ’² To Avoid ðŸ…¾ï¸Liquidation PLEASE ðŸ’µDEPOSIT*";}
else{
document.getElementById("Buyminl").innerHTML ="*Your Margin Level is : " +marginleveb +"% and Your ACCOUNT LIMIT is : "+Buyli +"ðŸ’²*";
}

}
function BFunction() {
  // Get the text field
  var copyText = document.getElementById("Buyminl");

  // Select the text field
  copyText.select;
// For mobile devices

  // Copy the text inside the text field
  navigator.clipboard.writeText(copyText.innerHTML);


}

<!-- Buy  limit for gram  Symbol-->


function Buygram() {
var grambuymargin = Number(document.getElementById("grambuymargin").value);

var buyrate=Number(document.getElementById("buyrate").value);

var buygramlimit=Math.ceil(buyrate-((grambuymargin*1.5)*0.19511)+5);
if (grambuymargin < 100) {document.getElementById("buygramoutput").innerHTML ="*âš ï¸WARNING: Your Margin Level is BELOWâ¬‡ï¸ SAFE LEVEL and it is : " +grambuymargin +"% and Your ACCOUNT LIMIT is : "+buygramlimit +"ðŸ’² To Avoid ðŸ…¾ï¸Liquidation PLEASE ðŸ’µDEPOSIT*";}
else{
document.getElementById("buygramoutput").innerHTML ="*Your Margin Level is : " +grambuymargin +"% and Your ACCOUNT LIMIT is : "+buygramlimit +"ðŸ’²*";
}

}
function buygramcopy() {
  // Get the text field
  var copyText = document.getElementById("buygramoutput");

  // Select the text field
  copyText.select;
// For mobile devices

  // Copy the text inside the text field
  navigator.clipboard.writeText(copyText.innerHTML);


}


<!--   Buy gm Traditional method-->


function BuyTrad() {
var Tpositionbuy = Number(document.getElementById("Tpositionbuy").value);

var RateTrbuy=Number(document.getElementById("ratebuyTr").value);

var Equitybuytr=Number(document.getElementById("equitybuy").value);

var buygramlimitTr=Math.ceil(RateTrbuy-((Equitybuytr*31.1035)/Tpositionbuy)+5);
var warningmessagebuy=Math.ceil((Equitybuytr*31.1035)/Tpositionbuy);
if (warningmessagebuy < 35) {document.getElementById("TrBuy").innerHTML ="*âš ï¸WARNING: Your Account Status is BELOWâ¬‡ï¸ SAFE LEVEL and Your Equity is : " +Equitybuytr +" $ and Your ACCOUNT LIMIT is : "+buygramlimitTr +" ðŸ’² To Avoid ðŸ…¾ï¸Liquidation PLEASE ðŸ’µDEPOSIT*";}
else{
document.getElementById("TrBuy").innerHTML ="*Your Equity is : " +Equitybuytr +" $ and Your ACCOUNT LIMIT is : "+buygramlimitTr +"ðŸ’²*";
}

}
function TGramBuy() {
  // Get the text field
  var copyText = document.getElementById("TrBuy");

  // Select the text field
  copyText.select;
// For mobile devices

  // Copy the text inside the text field
  navigator.clipboard.writeText(copyText.innerHTML);


}






// Ounce Limit Calculation


function Buyounce() {
var lotsize = Number(document.getElementById("grambuymarginounce").value);

var ozcurrentrate=Number(document.getElementById("buyouncerate").value);

var equityoz=Number(document.getElementById("buyounceequity").value);


var limitoz=Math.ceil(ozcurrentrate-(equityoz/(lotsize*100)));
document.getElementById("buyounceoutputt").innerHTML ="*Your Equity is: " +equityoz+" $ and Your ACCOUNT LIMIT is : "+limitoz +"ðŸ’²*";}

function buyouncecopy() {
  // Get the text field
  var copyText = document.getElementById("buyounceoutputt");

  // Select the text field
  copyText.select;
// For mobile devices

  // Copy the text inside the text field
  navigator.clipboard.writeText(copyText.innerHTML);


}

// Ounce Sell Limit Calculation


function Sellounce() {
var lotsizesell = Number(document.getElementById("sellounce").value);

var ozcurrentratesell=Number(document.getElementById("sellouncerate").value);

var equityozsell=Number(document.getElementById("sellounceequity").value);


var limitozsell=Math.ceil(ozcurrentratesell+(equityozsell/(lotsizesell*100)));
document.getElementById("sellounceoutputt").innerHTML ="*Your Equity is: " +equityozsell+" $ and Your ACCOUNT LIMIT is : "+limitozsell +"ðŸ’²*";}

function sellouncecopy() {
  // Get the text field
  var copyText = document.getElementById("sellounceoutputt");

  // Select the text field
  copyText.select;
// For mobile devices

  // Copy the text inside the text field
  navigator.clipboard.writeText(copyText.innerHTML);


}






</script>



<style>

#main{

border-radius: 6px;
margin-left: 55px;
}
.head {
padding:5px;
width: 990px;
font-size:25px;
font-family: 'Alata', sans-serif;
font-family: 'Bebas Neue', sans-serif;
font-family: 'Bungee', cursive;
font-family: 'Bungee Spice', cursive;
font-family: 'Handjet', cursive;
font-family: 'Russo One', sans-serif;
}
.rs {
padding:10px;
width: 990px;
font-size:30px;
text-align:left;
font-family: 'Alata', sans-serif;
font-family: 'Bebas Neue', sans-serif;
font-family: 'Bungee', cursive;
font-family: 'Bungee Spice', cursive;
font-family: 'Handjet', cursive;
font-family: 'Russo One', sans-serif;
}

.symbol{
font-family: 'Alata', sans-serif;
font-family: 'Bebas Neue', sans-serif;
font-family: 'Bungee', cursive;
font-family: 'Bungee Spice', cursive;
font-family: 'Handjet', cursive;
font-family: 'Rubik Mono One', sans-serif;
font-family: 'Russo One', sans-serif;
}


.box{

 border-radius: 15px;
  padding: 5px 8px;
  font-size: 15px;
  text-transform: uppercase
}

button {
  border: none;
  border-radius: 20px;
  padding: 12px 18px;
  font-size: 12px;
  text-transform: uppercase;
  cursor: pointer;
  background-color: #2196f3;
  box-shadow: 0 0 4px #999;
  outline: none;
  color: white;
}

.ripple {
  background-position: center;
  transition: background 0.9s;
}

.ripple:hover{
  background-color: #FF0000;
  background-image: radial-gradient(circle,transparent 1%,#47a7f5 1%);
  background-position: center;
  background-size: 15000%;
}

.ripple:active{
  transition: background 0s;
  background-color: #6eb9f7;
  background-size: 100%;
}

.fontstyle{
font-family: 'Bebas Neue', sans-serif;
font-family: 'Bungee', cursive;
font-family: 'Bungee Spice', cursive;
font-family: 'Handjet', cursive;
font-family: 'Russo One', sans-serif;
}
</style>

  </body>
</html>
